version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
  baza:
    image: mariadb
    volumes:
      - db_polbahasa:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: hasloroot
      MARIADB_USER: ahmosm
      MARIADB_PASSWORD: 1@qwerty
      MARIADB_DATABASE: polbahasa
    ports:
      - 3306:3306
volumes:
  db_polbahasa:
  elasticsearch_data: